language: node_js
 node_js:
   - "0.8"
   - "0.10"

 before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g grunt-cli karma bower
  - cd server
  - npm install --quiet
  - node server.js &
  - sleep 3 # give server some time to start
  - cd ../client
  - bower install
  - npm install --quiet

 script: grunt